// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealtorTool.Data;

#nullable disable

namespace RealtorTool.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250605114226_AddTagsForClients")]
    partial class AddTagsForClients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealtorTool.Core.DbModels.Dictionary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dictionaries");
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.DictionaryValue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DictionaryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.ToTable("DictionaryValues");
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.PersonModels.AuthorizationData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuthorizationData");
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.PersonModels.ClientTags", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clientTag_client")
                        .HasColumnType("text");

                    b.Property<string>("clientTag_tag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("clientTag_client");

                    b.HasIndex("clientTag_tag");

                    b.ToTable("ClientTags");
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.PersonModels.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EMail")
                        .HasColumnType("text");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.PersonModels.RealtorDetails", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AboutMe")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("Qualification")
                        .HasColumnType("text");

                    b.Property<string>("Services")
                        .HasColumnType("text");

                    b.Property<string>("WorkExperience")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RealtorDetails");
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.DictionaryValue", b =>
                {
                    b.HasOne("RealtorTool.Core.DbModels.Dictionary", "Dictionary")
                        .WithMany("DictionaryValues")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.PersonModels.AuthorizationData", b =>
                {
                    b.HasOne("RealtorTool.Core.DbModels.PersonModels.Person", null)
                        .WithOne("AuthorizationData")
                        .HasForeignKey("RealtorTool.Core.DbModels.PersonModels.AuthorizationData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.PersonModels.ClientTags", b =>
                {
                    b.HasOne("RealtorTool.Core.DbModels.PersonModels.Person", "Client")
                        .WithMany()
                        .HasForeignKey("clientTag_client")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RealtorTool.Core.DbModels.DictionaryValue", "Tag")
                        .WithMany()
                        .HasForeignKey("clientTag_tag")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.PersonModels.Person", b =>
                {
                    b.HasOne("RealtorTool.Core.DbModels.DictionaryValue", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.PersonModels.RealtorDetails", b =>
                {
                    b.HasOne("RealtorTool.Core.DbModels.PersonModels.Person", null)
                        .WithOne("RealtorDetails")
                        .HasForeignKey("RealtorTool.Core.DbModels.PersonModels.RealtorDetails", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.Dictionary", b =>
                {
                    b.Navigation("DictionaryValues");
                });

            modelBuilder.Entity("RealtorTool.Core.DbModels.PersonModels.Person", b =>
                {
                    b.Navigation("AuthorizationData");

                    b.Navigation("RealtorDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
